### ISSUE TITLE
Version 0.9.1 - terminate called after throwing an instance of 'StdFail_NotDone'

### ISSUE THREAD

**Issue by mrmoss** [miho/OCC-CSG#5]
Getting this error on a stock Ubuntu 18.04 machine for any STL I give it (random models from around the internet and generated objects from occ-csg).

Full output:
```
$ occ-csg --create box 0,0,0,10,10,10 box.stl
------------------------------------------------------------
------      CSG Tool based on the OCE CAD Kernel      ------
------                 Version 0.9.1                  ------
------ 2018 by Michael Hoffer (info@michaelhoffer.de) ------
------                www.mihosoft.eu                 ------
------------------------------------------------------------
> saving geometry
 -> writing file 'box.stl'
 -> STL TOL: 0.5
 -> done.
$ occ-csg --edit round-edges 20 box.stl box-rounded.stl
------------------------------------------------------------
------      CSG Tool based on the OCE CAD Kernel      ------
------                 Version 0.9.1                  ------
------ 2018 by Michael Hoffer (info@michaelhoffer.de) ------
------                www.mihosoft.eu                 ------
------------------------------------------------------------
> loading geometry
 -> reading file 'box.stl'
> importing STL file
 -> reading 'box.stl'
 -> converting to faces
 -> sewing faces
 -> extracting shells
   -> shells found: 1
 -> converting to solid
 -> done.
 -> done.
terminate called after throwing an instance of 'StdFail_NotDone'
Aborted (core dumped)
```

**Comment by miho** [comment]
The radius you specified for rounding the edges is to large for the box you specified. A radius of 20 would require a box with w,h,d > 40. For a box with dimensions `(10,10,10)` a radius < 5 would work, e.g. 4.9. bit that would essentially result in a sphere.

And please don't use STL for the intermediate steps since this will significantly reduce the quality of the result. STL is not resolution independent. `.stp` and `.brep` are fine. 

So this would be the recommended way of rounding the box:

```
occ-csg --create box 0,0,0,10,10,10 box.brep
occ-csg --edit round-edges 2 box.stp box-rounded.stl
```

Here's the result:

![screenshot 2018-08-15 17 59 18](https://user-images.githubusercontent.com/225266/44158441-f2a11300-a0b4-11e8-9f50-0f7348242ce2.png)

**Comment by mrmoss** [comment]
Roger that, thanks.
